name: Default
on:
  push:
    paths-ignore:
      - readme.md
    branches:
      - master
jobs:
  integration:
    name: Builds a project and uploads all required files into the remote machine
    runs-on: ubuntu-18.04
    env:
      ELEVENTY_ENV: production
    steps:
      - uses: actions/checkout@master
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > ~/.npmrc
      - name: Use required JavaScript runtime environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install project dependencies
        run: npm install
      - name: Build a project
        run: npm run 11ty:build
      - name: Start transferring files into the remote machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          source: "dist/*,dockerfile,nginx/*"
          target: "baythium-projects/baythium-packer_client"
          rm: true
  deployment:
    name: Connects to the remote machine and builds an image using Docker with further requirements
    runs-in: ubuntu-18.04
    needs: integration
    env:
      NAME: "Baythium Packer"
      URL: "https://packer.baythium.com"
      PATH: "baythium-projects/baythium-packer_client"
    steps:
      - name: Start deploying
        uses: appleboy/ssh-action@master
        with:
          envs: NAME,URL,PROJECT_LOCATION
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
          timestamp=$(date +%s)
          cd $PATH
          docker rm $(docker stop $(docker ps --filter "name=baythium-packer_client" --format="{{.ID}}"))
          docker rmi $(docker images | grep "baythium-packer_client")
          docker build . --file dockerfile --tag baythium-ecosystem/baythium-packer_client:$timestamp
          docker run -d --name baythium-packer_client --expose 10033 --net baythium-network-1 -e "VIRTUAL_HOST=packer.baythium.com, packer.bayesianflow.space" --restart=on-failure:3 baythium-ecosystem/baythium-packer_client:$timestamp