name: Default
on:
  push:
    paths-ignore:
      - readme.md
    branches:
      - master
jobs:
  deployment:
    name: Connects to the remote machine and builds an image using Docker with further requirements
    runs-on: ubuntu-18.04
    steps:
      - name: Start deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            groups