name: Default
on:
  push:
    paths-ignore:
      - readme.md
    branches:
      - master
jobs:
  deployment:
    name: Connects to the remote machine and builds an image using Docker with further requirements
    runs-on: ubuntu-18.04
    steps:
      - name: Start deploying
        uses: appleboy/ssh-action@master
        env:
          VPATH: baythium-projects/baythium-packer_client
          VNAME: baythium-packer_client
          VHOST: packer.baythium.com,packer.bayesianflow.space
          VNETWORK: baythium-network-1
          VPREFIX: baythium-ecosystem
          VPORT: 10033
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          envs: VPATH,VNAME,VHOST,VNETWORK,VPREFIX,VPORT
          script: |
            timestamp=$(date +%s)
            cd $VPATH
            docker rm $(docker stop $(docker ps --filter "name=$VNAME" --format="{{.ID}}"))
            docker rmi $(docker images | grep "$VNAME")
            docker build . --file dockerfile --tag $VPREFIX/$VNAME:$timestamp
            docker run -d --name $VNAME --expose $VPORT --net $VNETWORK -e "VIRTUAL_HOST=$VHOST" --restart=on-failure:3 $VPREFIX/$VNAME:$timestamp