name: Default

on:
  push:
    paths-ignore:
      - readme.md
      - docs/
    branches:
      - master

jobs:
  integration:
    name: Builds a project and uploads all required files into the remote machine
    if: ${{ contains(github.event.head_commit.message, '[publish]') || contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-18.04
    env:
      ELEVENTY_ENV: production
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@master

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > .npmrc

      - name: Use required JavaScript runtime environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/

      - name: Install project dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}

      - name: 🔧 Build a project
        run: npm run 11ty:build

      - name: Start transferring files into the remote machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          source: "dist/*,dockerfile,nginx/*"
          target: "baythium-projects/bth-packer_11ty-client"
          rm: true

  deployment:
    name: Connects to the remote machine and builds an image using Docker with further requirements
    runs-on: ubuntu-18.04
    needs: integration
    steps:
      - name: 🚀 Start deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            cd baythium-projects/bth-packer_11ty-client
            ids=$(docker ps -a --filter "name=bth-packer_11ty-client" --format="{{.ID}}")
            [[ -n $ids ]] && docker stop $ids && docker rm $ids 
            images=$(docker images -a | grep "bth-packer_11ty-client" | awk '{print $1":"$2}')
            [[ -n $images ]] && docker rmi $images
            timestamp=$(date +%s) 
            docker build . --rm --file dockerfile --tag baythium-ecosystem/bth-packer_11ty-client:$timestamp
            docker run -d --name bth-packer_11ty-client --net baythium-network-1 --ip 172.18.0.42 -p 127.0.0.1:10033:80 --restart=on-failure:3 baythium-ecosystem/bth-packer_11ty-client:$timestamp
