name: Default
on:
  push:
    paths-ignore:
      - readme.md
    branches:
      - master
jobs:
  deployment:
    name: Connects to the remote machine and builds an image using Docker with further requirements
    runs-on: ubuntu-18.04
    steps:
      - name: Start deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            timestamp=$(date +%s)
            cd baythium-projects/baythium-packer_client
            docker rm $(docker stop $(docker ps --filter "name=baythium-packer_client" --format="{{.ID}}"))
            docker rmi $(docker images | grep "baythium-packer_client")
            docker build . --file dockerfile --tag baythium-ecosystem/baythium-packer_client:$timestamp
            docker run -d --name baythium-packer_client --expose 10033 --net baythium-network-1 -e "VIRTUAL_HOST=packer.baythium.com,packer.bayesianflow.space" --restart=on-failure:3 baythium-ecosystem/baythium-packer_client:$timestamp