name: Deploy

on:
  push:
    paths-ignore:
      - readme.md
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file dockerfile --tag baythium-ecosystem/baythium-packer_client:$(date +%s)
