name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: nginx:1.16.1

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag baythium-ecosystem/baythium-packer_client:$(date +%s)
