name: Integration
on:
  push:
    paths-ignore:
      - readme.md
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install project dependencies
        run: npm install
        run: npm run 11ty:build --if-present
